### ISSUE TITLE
Installing SpaceMarkers Error

### ISSUE THREAD

**Issue by mloberg16** [DeshpandeLab/SpaceMarkers#8]
Hello, thanks for making this tool. When I try to install SpaceMarkers (currently using R 4.3.1), I get an error that one of the dependencies ('spatstat.core') is not available and therefore the installation will not work. Looking into spatstat.core, it seems that it was archived on 2022-12-12 and removed from the CRAN repository. Is there a newer release of SpaceMarkers that does not have the spatstat.core dependency or a workaround solution for installing spacemarkers?

Thanks so much for your help. 
Matt

**Comment by atuldeshpande** [comment]
Should be fixed with the latest merge.
